### ISSUE TITLE
We need a landing page

### ISSUE THREAD

**Issue by timlinux** [kartoza/InWARDS-Dashboard-Desktop#8]
It should show a map with WMA's

The user should be able to choose one or more of the catchments on the map, or by using a checkbox list of the WMA's

<img width="1276" alt="image" src="https://user-images.githubusercontent.com/178003/73166645-211a7e80-40ee-11ea-9dc7-f00fef118b69.png">

This page should be shown every time you open the app

The user should be able to return to this page once they have entered the dashboard

We need a button to dispatch the landing page once they have made their selection.

The JSON used to display the WMA's should be baked into the app as a local asset

See #5

**Comment by surfer23** [comment]
SO I have been playing around and created a little mock up, what about we add the latest flow reading to each unverified station marker on entry. We can also have a left panel scroll-able table which allows us to quickly select a site where we just want to view the weekly discharge timeseries? 
Mock Up:
http://inwards.award.org.za/interface_samples/landingpage.html


![image](https://user-images.githubusercontent.com/17697540/73245839-dfeda180-41b5-11ea-94b9-67265d51634e.png)


![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/17697540/73246506-740c3880-41b7-11ea-93a2-b4feeb6d2103.gif)

**Comment by timlinux** [comment]
@hugo I wonder if we aren't mixing messages here. If I am the user it is no longer clear what is expected of me on this page since it serves two purposes now
1) browing guaging stations
2) selecting a WMA to use for the dashboard

I would suggest moving 1) above into a separate view 'quick browser' or something which can be linked off the landing page as an alternative to the dashboard page link which would appear under your checkbox panel.

What do you think?

**Comment by surfer23** [comment]
Great agree with you Tim, separate view 'quick browser' sounds good. I just think a overview dash would be a nice way of seeing status of gauges without having to drill individually through each stations dashboard. Ok cool so we will put this feature on the back burner for now
